#!/usr/bin/env bash
set -euo pipefail

# Generate SQL to create databases, users and grants from env vars
cat > /docker-entrypoint-initdb.d/20-create-dbs.sql <<SQL
CREATE DATABASE IF NOT EXISTS \`${AUTH_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${LICENSE_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${LOOP_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${KRATOS_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${HYDRA_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${AUTH_DB_USER}'@'%' IDENTIFIED BY '${AUTH_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${AUTH_DB_NAME}\`.* TO '${AUTH_DB_USER}'@'%';

CREATE USER IF NOT EXISTS '${LICENSE_DB_USER}'@'%' IDENTIFIED BY '${LICENSE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${LICENSE_DB_NAME}\`.* TO '${LICENSE_DB_USER}'@'%';

CREATE USER IF NOT EXISTS '${LOOP_DB_USER}'@'%' IDENTIFIED BY '${LOOP_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${LOOP_DB_NAME}\`.* TO '${LOOP_DB_USER}'@'%';

CREATE USER IF NOT EXISTS '${KRATOS_DB_USER}'@'%' IDENTIFIED BY '${KRATOS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${KRATOS_DB_NAME}\`.* TO '${KRATOS_DB_USER}'@'%';

CREATE USER IF NOT EXISTS '${HYDRA_DB_USER}'@'%' IDENTIFIED BY '${HYDRA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${HYDRA_DB_NAME}\`.* TO '${HYDRA_DB_USER}'@'%';

FLUSH PRIVILEGES;
SQL

# Ensure sensible permissions
chmod 644 /docker-entrypoint-initdb.d/20-create-dbs.sql
